# Generated by Django 5.2.6 on 2025-11-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairpriceApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='crop_images/'),
        ),
    ]
