# Generated by Django 5.2.6 on 2025-11-28 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairpriceApp', '0002_cropmodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_histories', to='fairpriceApp.cropmodel')),
            ],
            options={
                'ordering': ['year'],
                'unique_together': {('crop', 'year')},
            },
        ),
    ]
