# Generated by Django 5.2.6 on 2026-01-02 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairpriceApp', '0004_user_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('govt', 'Government'), ('admin', 'Admin'), ('agent', 'Agent')], default='agent', max_length=10),
        ),
    ]
