# Generated by Django 5.2.6 on 2026-01-02 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairpriceApp', '0005_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='site_content/')),
                ('mission_image', models.ImageField(blank=True, null=True, upload_to='site_content/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page Content',
                'verbose_name_plural': 'About Page Content',
            },
        ),
    ]
