# Generated by Django 5.2.6 on 2026-01-02 02:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairpriceApp', '0006_aboutpagecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivationcostcalculator',
            name='fertilizer_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='cultivationcostcalculator',
            name='irrigation_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='cultivationcostcalculator',
            name='labor_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='cultivationcostcalculator',
            name='pesticide_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='farmertowarehousemodel',
            name='quantity_kg',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity (KG)'),
        ),
        migrations.AddField(
            model_name='farmertowarehousemodel',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Price per KG', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='cultivationcostcalculator',
            name='cultivation_area',
            field=models.DecimalField(decimal_places=2, help_text='Area in Acres', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='cultivationcostcalculator',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='farmertowarehousemodel',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
